### ISSUE TITLE
keyword on message

### ISSUE THREAD

**Issue by mr-smit** [daniele-athome/dovecot-virtual-keywords-plugin#3]
Hello

Nice plugin, I have some questions:

I want Gmail like Labels. You are writing: **"A plugin that automatically creates a virtual mailbox when a new keyword is set on a message."**

Question is: How to set keyword on message? with php somehow? imap command?

http://php.net/manual/en/function.imap-setflag-full.php

something like this ?:

`$status = imap_setflag_full($mbox, "2,5", "\\Seen \\Flagged \\My_new_label");`

**Comment by daniele-athome** [comment]
I don't remember the exact syntax but yes, keywords are actually IMAP flags. No beginning backslash though, that's reserved for internal IMAP flags. Just use plain words.

**Comment by daniele-athome** [comment]
A small note your wish on Gmail-like labels. That's nearly impossible to achieve with IMAP, however this plugin tries to get close to that by providing special virtual folders. But those will be IMAP folders, for clients they will be like physical folders, meaning duplicate messages for example. I'm trying to write a set of plugins to achieve real Gmail labels but it'll be a long journey :-)

**Comment by mr-smit** [comment]
so after I set a flag "my_label" on message, what happens ?
it will appear in virtual folder my_label and if I delete it from my_label it will be automatically deleted from Inbox folder too and vice versa ?

**Comment by mr-smit** [comment]
I just compiled and started plugin but its crashing imap

imap[22784]: segfault at 138800001388 ip 00007eff12cc1cc0 sp 00007ffc08a99b80 error 4 in libc-2.23.so[7eff12c73000+1c0000]

imap: Fatal: master: service(imap): child 22784 killed with signal 11 (core dumped)

**Comment by daniele-athome** [comment]
> so after I set a flag "my_label" on message, what happens ?

The plugin will create a virtual folder "my_label" under [the namespace you configured](https://github.com/daniele-athome/dovecot-virtual-keywords-plugin#dovecot-configuration).

> it will appear in virtual folder my_label and if I delete it from my_label it will be automatically deleted from Inbox folder too and vice versa ?

Yes. That's why I said reaching Gmail-like functionality will be hard to do with IMAP :-) it requires a whole new file system driver for Dovecot to handle all these little things correctly.

**Comment by daniele-athome** [comment]
> I just compiled and started plugin but its crashing imap

Get a backtrace from the core dump with gdb and we can see if there is a problem with the plugin. It's most probably wrong Dovecot configuration (I've been running this plugin for months without problems, but as always YMMV).
