### ISSUE TITLE
Pidgeonhole & Mailur

### ISSUE THREAD

**Issue by guyest** [daniele-athome/dovecot-virtual-keywords-plugin#4]
If this problem is still of interest, you may want to take a look at https://github.com/naspeh/mailur for a more ambitious attempt at an implementation or https://pigeonhole.dovecot.org/ for a tool to implement it yourself.

**Comment by daniele-athome** [comment]
Thanks for the suggestion! I don't have much time to spend for this, the plugin works well enough anyway. I'll take a look at Pigeonhole to see if I can find some ispiration.
Mailur is nice, however I need something server-side with some abstraction layers (e.g. a virtual file system) so I can map keywords-related actions to normal IMAP manipulation actions (e.g. Android).
